# Generated by Django 5.2.5 on 2025-09-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
