# Generated by Django 5.2.5 on 2025-09-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_website_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ssl_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='ssl_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
