# Generated by Django 5.2.5 on 2025-09-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_website_ssl_error_message_website_ssl_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed_mbps', models.FloatField()),
                ('upload_speed_mbps', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
